import Vue from "vue";
import LinkHome from "../components/Global/LinkHome.vue";
import Tilt from "../components/Global/Tilt.vue";
import ParticlesBackground from "../components/Global/ParticlesBackground.vue";
import InteractiveBackground from "../components/Global/InteractiveBackground.vue";
import InteractiveGradient from "../components/Global/InteractiveGradient.vue";
import SectionContainer from "../components/Global/SectionContainer.vue";
import CookieConsent from "../components/Global/CookieConsent.vue";
import BookNow from "../components/Global/BookNow.vue";
import MembershipLink from "../components/Global/MembershipLink.vue";

Vue.component("link-home", LinkHome);
Vue.component("tilt", Tilt);
Vue.component("particles-background", ParticlesBackground);
Vue.component("interactive-background", InteractiveBackground);
Vue.component("interactive-gradient", InteractiveGradient);
Vue.component("section-container", SectionContainer);
Vue.component("cookie-consent", CookieConsent);
Vue.component("book-now", BookNow);
Vue.component("membership-link", MembershipLink);
